### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'cdouble'

### ISSUE THREAD

**Issue by rraminen** [seemethere/pytorch-compat-test#1]
While running the pytorch-compat-tests for ubuntu-16.04 and ubuntu-18.04, AttributeError: module 'torch' has no attribute 'cdouble' comes up.

Command: make -f docker.Makefile ubuntu-16.04 ubuntu-18.04 

Pytorch installed :  pytorch-test/linux-64::pytorch-1.5.1-py3.7_cpu_0

```
Traceback (most recent call last):
  File "test_autograd.py", line 6575, in <module>
    add_test(*test)
  File "test_autograd.py", line 4362, in add_test
    for dtype in [torch.double, torch.cdouble]:
AttributeError: module 'torch' has no attribute 'cdouble'
Traceback (most recent call last):
  File "run_test.py", line 726, in <module>
    main()
  File "run_test.py", line 719, in main
    raise RuntimeError(message)
RuntimeError: test_autograd failed!
```
cc: @jithunnair-amd

**Comment by seemethere** [comment]
You probably need to specify `PYTORCH_REF=v1.5.1` in order to get the correct tests for `v1.5.1`.

This was added as part of https://github.com/seemethere/pytorch-compat-test/commit/6fd288539a5d4e863d500c1ff6810f0bdeb105fb

There should probably be some documentation on this somewhere.

**Comment by rraminen** [comment]
Thanks for your reply. 
I tried with` PYTORCH_REF=v1.5.1`. The same error, `AttributeError: module 'torch' has no attribute 'cdouble'` , is coming up. Is there anything else that I could try?

**Comment by rraminen** [comment]
The script is working after specifying` PYTORCH_REF:= v1.5.1` in docker.Makefile. Thank you.
